package(default_visibility = ["//tools/android:__pkg__"])

filegroup(
    name = "srcs",
    srcs = glob(["*"]),
)

filegroup(
    name = "embedded_tools",
    srcs = [
        "BUILD.tools",
        "googletest.sh",
        "no_se_linux.properties",
        "snapshots.img.zip",
    ],
)
