package(default_visibility = ["//src:__subpackages__"])

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:srcs",
        "//src/java_tools/import_deps_checker/javatests/com/google/devtools/build/importdeps:srcs",
    ],
)
