package(default_visibility = ["//visibility:public"])

filegroup(
    name = "runtime",
    srcs = ["test-setup.sh"],
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "test-setup.sh",
    ],
)
