licenses(["notice"])  # Apache 2.0

package_group(
    name = "loose_header_check_allowed_in_toolchain",
    packages = [],
)

filegroup(
    name = "srcs",
    srcs = ["BUILD"],
    visibility = ["//tools/build_defs:__pkg__"],
)
