package(default_applicable_licenses = ["//:license"])

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "//src/test/java/net/starlark/java/annot/processor:srcs",
        "//src/test/java/net/starlark/java/eval:srcs",
        "//src/test/java/net/starlark/java/spelling:srcs",
        "//src/test/java/net/starlark/java/syntax:srcs",
    ],
    visibility = ["//src:__pkg__"],
)
