# Description:
#   C++ utility tests for Bazel

cc_test(
    name = "blaze_util_test",
    srcs = ["blaze_util_test.cc"],
    deps = [
        "//src/main/cpp:blaze_util",
        "//src/main/cpp/util",
        "//third_party:gtest",
    ],
)

test_suite(
    name = "all_tests",
)
