package(default_visibility = ["//visibility:public"])

alias(
    name = "javalite",
    actual = "//external:proto/toolchains/javalite",
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
    ],
    visibility = ["//tools:__pkg__"],
)
