package(default_visibility = ["//visibility:public"])

ios_device(
    name = "default",
    ios_version = "8.4",
    type = "IPHONE",
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//tools/objc:__pkg__"],
)
