filegroup(
    name = "srcs",
    srcs = glob(["*"]) + [
        "//configs/rbe/rbe_ubuntu1604_java8:srcs",
        "//configs/rbe/rbe_ubuntu1804_java11:srcs",
    ],
    visibility = ["//configs:__pkg__"],
)
