# Stub tools for the upcoming Jack support in Bazel.

package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "jack",
    srcs = ["fail.sh"],
)

sh_binary(
    name = "jill",
    srcs = ["fail.sh"],
)

sh_binary(
    name = "resource_extractor",
    srcs = ["fail.sh"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)
