exports_files(
    [
        "command-line-reference-prefix.html",
        "command-line-reference-suffix.html",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + ["//site/en:srcs"],
    visibility = ["//:__pkg__"],
)
