# Whitelists for restricting access to Bazel features.

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "//tools/whitelists/config_feature_flag:srcs",
    ],
    visibility = ["//tools:__pkg__"],
)
