package(default_visibility = ["//visibility:private"])

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "BUILD.tools",
        "//tools/java/runfiles:srcs",
    ],
    visibility = ["//tools:__pkg__"],
)

filegroup(
    name = "embedded_tools",
    srcs = [
        "BUILD.tools",
        "//tools/java/runfiles:embedded_tools",
    ],
    visibility = ["//tools:__pkg__"],
)
