steps:
#  - command: "buildkite-agent pipeline upload"
#    label: ":pipeline:"
  - command: "install_bazel.sh"
    key: "install_bazel"
  - command: "bazel build //src:bazel-dev"
    key: "bazel_build"
    depends_on: "install_bazel"
    retry:
      automatic:
        - exit_status: "*"
          limit: 4
  - command: "bazel test //..."
    key: "bazel_test"
    depends_on: "bazel_build"
