package(default_visibility = ["//visibility:public"])

filegroup(
    name = "embedded_tools",
    srcs = [
        "BUILD",
        "BUILD.sdk",
        "sdk.bzl"
    ]
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "BUILD.sdk",
        "sdk.bzl"
    ]
)
