package(default_visibility = ["//visibility:public"])

exports_files(glob(["*"]) + ["jdk"])

filegroup(
    name = "headers",
    srcs = glob([
        "jdk/include/*.h",
        "jdk/include/*/*.h",
    ]),
)
