filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "maven_android_install.json",
        "//src/tools/android/java/com/google/devtools/build/android:BUILD",
        "//src/tools/android/java/com/google/devtools/build/android/dexer:BUILD",
        "//src/tools/android/java/com/google/devtools/build/android/idlclass:BUILD",
        "//src/tools/android/java/com/google/devtools/build/android/resources:BUILD",
        "//src/tools/android/java/com/google/devtools/build/android/ziputils:BUILD",
    ],
    visibility = ["//src:__pkg__"],
)
