filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//configs/rbe/rbe_ubuntu1604_java8/cc:srcs",
        "//configs/rbe/rbe_ubuntu1604_java8/java:srcs",
        "//configs/rbe/rbe_ubuntu1604_java8/config:srcs",
    ],
    visibility = ["//configs/rbe:__subpackages__"],
)
