package(default_visibility = ["//visibility:public"])

filegroup(
    name = "greeting",
    srcs = ["greeting.txt"],
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "greeting.txt",
    ],
)
