licenses(["notice"])  # Apache 2.0

exports_files(["action_names.bzl"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = [
        "//:__pkg__",
        "//tools:__pkg__",
    ],
)
