filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = [
        "//tools/proto/private:__pkg__",
    ],
)

filegroup(
    name = "bzl_srcs",
    srcs = glob(["*.bzl"]),
    visibility = [
        "//tools/proto/private:__pkg__",
    ],
)
