package(default_visibility = ["//visibility:public"])

filegroup(
    name = "coverage_support",
    srcs = ["collect-coverage.sh"],
)

filegroup(
    name = "coverage_report_generator",
    srcs = ["dummy_coverage_report_generator"],
)

filegroup(
    name = "srcs",
    srcs = glob(["*"]),
)
