package(default_visibility = ["//visibility:public"])

exports_files(glob(["**"]))

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)

py_library(
    name = "j2objc_wrapper",
    srcs = ["j2objc_wrapper.py"],
)
