package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//examples/cpp:srcs",
        "//examples/gen:srcs",
        "//examples/java-native:srcs",
        "//examples/java-starlark:srcs",
        "//examples/py:srcs",
        "//examples/py_native:srcs",
        "//examples/shell:srcs",
        "//examples/windows/dll:srcs",
    ],
)
