package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = [
        "//examples/cpp:srcs",
        "//examples/gen:srcs",
        "//examples/java-native:srcs",
        "//examples/java-skylark:srcs",
        "//examples/objc:srcs",
        "//examples/proto:srcs",
        "//examples/py:srcs",
        "//examples/py_native:srcs",
        "//examples/shell:srcs",
    ],
)
