package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//examples/android/java/bazel:srcs",
        "//examples/cpp:srcs",
        "//examples/gen:srcs",
        "//examples/java-native:srcs",
        "//examples/java-skylark:srcs",
        "//examples/j2objc:srcs",
        "//examples/objc:srcs",
        "//examples/py:srcs",
        "//examples/py_native:srcs",
        "//examples/shell:srcs",
        "//examples/swift:srcs",
        "//examples/windows/dll:srcs",
    ],
)
