package(default_visibility = ["//src:__subpackages__"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//src/tools/xcode-common/java/com/google/devtools/build/xcode/common:srcs",
        "//src/tools/xcode-common/java/com/google/devtools/build/xcode/util:srcs",
        "//src/tools/xcode-common/java/com/google/devtools/build/xcode/zip:srcs",
    ],
)
