# TODO(bazel-team): support darwin.

filegroup(
    name = "toolchain",
    srcs = ["@golang-linux-amd64//:toolchain"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "go_tool",
    srcs = ["@golang-linux-amd64//:go_tool"],
    visibility = ["//visibility:public"],
)
