package(
    default_visibility = [
        "//tools/build_defs/docker:__subpackages__",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)

filegroup(
    name = "test-data",
    srcs = ["test"],
)
