test_suite(
    name = "all_windows_tests",
    tests = [
        "//tools/build_defs/docker:all_windows_tests",
        "//tools/build_defs/hash:all_windows_tests",
        "//tools/build_defs/pkg:all_windows_tests",
    ],
    visibility = ["//tools:__pkg__"],
)
