workspace(name="py_sdk")

load("@bazel_tools//tools/python/sdk:sdk.bzl", "py_download_sdk")
py_download_sdk(
    name = "python3.7",
    version = "3.7.1",
    sha256 = "fa7e2b8e8c9402f192ad56dc4f814089d1c4466c97d780f5e5acc02c04243d6d"
)
py_download_sdk(
    name = "python2.7",
    version = "2.7.12",
    sha256 = "d7837121dd5652a05fef807c361909d255d173280c4e1a4ded94d73d80a1f978"
)

register_toolchains(
    "//:downloaded_sdk_toolchain"
)
