licenses(["notice"])  # Apache 2.0

package_group(
    name = "disabling_parse_headers_and_layering_check_allowed",
    packages = [],
)

filegroup(
    name = "srcs",
    srcs = ["BUILD"],
    visibility = ["//tools/build_defs:__pkg__"],
)
