#!/bin/sh

set -eu

if [ $# != 2 ]; then
   echo "Usage: $0 <so> <interface so>" 1>&2
   exit 1
fi

has_versioned_symbol() {
  "$NM" --dynamic --format=just-symbols --no-sort "$1" \
    | grep --quiet --max-count=1 --fixed-strings @
}

if has_versioned_symbol "$1"; then
  exec cp "$1" "$2"
else
  "$LLVM_IFS" --input-format=ELF "$1" --output-elf "$2"
fi
