package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//examples/java-starlark/src/main/java/com/example/myproject:srcs",
        "//examples/java-starlark/src/main/resources:srcs",
        "//examples/java-starlark/src/test/java/com/example/myproject:srcs",
    ],
)
