load(
    ":cache.bzl",
    "CANONICAL_ID_DOC",
    "DEFAULT_CANONICAL_ID_ENV",
)

load(
    ":utils.bzl",
    "patch",
    "update_attrs",
    "workspace_and_buildfile",
)

_common_attrs = {
    "remote": attr.string(
        mandatory = True,
        doc = "The URI of the remote Mercurial repository. If using " +
	            "url#branch format, the branch given here is only used if " +
	            "the 'revision' and 'branch' field are NOT set.",
    ),
    "revision": attr.string(
        default = "",
        doc = "The revision to be checked out.",
    ),
    "branch": attr.string(
        default = "",
        doc = "The branch in the remote repository to checked out." +
              " Only used if the 'revision' attribute is not set.",
    ),
    "canonical_id": attr.string(
        doc = CANONICAL_ID_DOC,
    ),
    "verbose": attr.bool(default = False),
    "strip_prefix": attr.string(
        default = "",
        doc = "A directory prefix to strip from the extracted files.",
    ),
    "patches": attr.label_list(
        default = [],
        doc =
            "A list of files that are to be applied as patches after " +
            "extracting the archive. By default, it uses the Bazel-native patch implementation " +
            "which doesn't support fuzz match and binary patch, but Bazel will fall back to use " +
            "patch command line tool if `patch_tool` attribute is specified or there are " +
            "arguments other than `-p` in `patch_args` attribute.",
    ),
    "patch_tool": attr.string(
        default = "",
        doc = "The patch(1) utility to use. If this is specified, Bazel will use the specified " +
              "patch tool instead of the Bazel-native patch implementation.",
    ),
    "patch_args": attr.string_list(
        default = [],
        doc =
            "The arguments given to the patch tool. Defaults to -p0 (see the `patch_strip` " +
            "attribute), however -p1 will usually be needed for patches generated by " +
            "git. If multiple -p arguments are specified, the last one will take effect." +
            "If arguments other than -p are specified, Bazel will fall back to use patch " +
            "command line tool instead of the Bazel-native patch implementation. When falling " +
            "back to patch command line tool and patch_tool attribute is not specified, " +
            "`patch` will be used.",
    ),
    "patch_strip": attr.int(
        default = 0,
        doc = "When set to `N`, this is equivalent to inserting `-pN` to the beginning of `patch_args`.",
    ),
    "patch_cmds": attr.string_list(
        default = [],
        doc = "Sequence of Bash commands to be applied on Linux/Macos after patches are applied.",
    ),
    "patch_cmds_win": attr.string_list(
        default = [],
        doc = "Sequence of Powershell commands to be applied on Windows after patches are " +
              "applied. If this attribute is not set, patch_cmds will be executed on Windows, " +
              "which requires Bash binary to exist.",
    ),
    "remote_patches": attr.string_dict(
        default = {},
        doc =
            "A map of patch file URL to its integrity value, they are applied after cloning " +
            "the repository and before applying patch files from the `patches` attribute. " +
            "It uses the Bazel-native patch implementation, you can specify the patch strip " +
            "number with `remote_patch_strip`",
    ),
    "remote_patch_strip": attr.int(
        default = 0,
        doc =
            "The number of leading slashes to be stripped from the file name in the remote patches.",
    ),
    "build_file": attr.label(
        allow_single_file = True,
        doc =
            "The file to use as the BUILD file for this repository. " +
            "This attribute is an absolute label (use '@//' for the main " +
            "repo). The file does not need to be named BUILD, but can " +
            "be (something like BUILD.new-repo-name may work well for " +
            "distinguishing it from the repository's actual BUILD files). ",
    ),
    "build_file_content": attr.string(
        doc =
            "The content for the BUILD file for this repository. ",
    ),
}


def _mercurial_repository_implementation(ctx):
    if ctx.attr.build_file and ctx.attr.build_file_content:
        fail("Only one of build_file and build_file_content can be provided.")

    # Directory to place mercurial repository.
    root = ctx.path(".")
    directory = str(root)
    if ctx.attr.strip_prefix:
        directory = str(root.get_child(".tmp_hg_root"))

    changeset_id = _clone_repo(ctx, directory)
    if ctx.attr.verbose:
        print("hg.bzl: Cloning %s repository using strip_prefix of [%s]" %
              (
                  ctx.name,
                  ctx.attr.strip_prefix if ctx.attr.strip_prefix else "None",
              ))

    # Apply strip_prefix.
    if ctx.attr.strip_prefix:
        dest_link = "{}/{}".format(directory, ctx.attr.strip_prefix)
        if not ctx.path(dest_link).exists:
            fail("strip_prefix at {} does not exist in repo".format(ctx.attr.strip_prefix))
        for item in ctx.path(dest_link).readdir():
            ctx.symlink(item, root.get_child(item.basename))

    workspace_and_buildfile(ctx)
    patch(ctx)

    # Remove hg metadta.
    if ctx.attr.strip_prefix:
        ctx.delete(ctx.path(".tmp_hg_root/.hg"))
    else:
        ctx.delete(ctx.path(".hg"))

   # To get a reproducible version, the full changeset id must be used.
    if ctx.attr.revision == changeset_id:
        return ctx.repo_metadata(reproducible=True)
    return ctx.repo_metadata(
        attrs_for_reproducibility=_update_hg_attrs(
            ctx.attr, _common_attrs.keys(), {"revision": changeset_id}
        )
    )


def _clone_repo(ctx, directory):
    """Clones the mercurial repository to the working repository directory.

    Args:
        ctx: Context of the calling rules, for reading the attributes.
        Please refer to mercurial_repository for the description.
	      directory: Directory where to check out the file tree.
    Returns:
        Full changeset id of the repository working directory.
    """
    clone_args = ["clone"]
    clone_progress_msg = ["Cloning %s" % ctx.attr.remote]

    if ctx.attr.revision:
        clone_args.extend(["--rev", ctx.attr.revision])
        clone_progress_msg.append("at revision %s" % ctx.attr.revision)
    if ctx.attr.branch:
        clone_args.extend(["--branch", ctx.attr.branch])
        clone_progress_msg.append("at branch %s" % ctx.attr.branch)

    clone_args.append(ctx.attr.remote)
    clone_args.append(directory)

    ctx.report_progress(" ".join(clone_progress_msg))
    st = _hg_execute(ctx, clone_args, directory)
    if st.return_code != 0:
        _hg_error(ctx.name, clone_args, st.stderr)

    # Get the full changeset id (40-digit hexadecimal string)
    id_args = ["id", "--id", "--debug"]
    st = _hg_execute(ctx, id_args, directory)
    if st.return_code != 0:
        _hg_error(ctx.name, id_args, st.stderr)

    return st.stdout.strip()


def _hg_execute(ctx, args, working_directory):
    return ctx.execute(
        ["hg"] + args,
        environment=(
            ctx.os.environ
            | {
	              # List of variables to unset when calling `hg` to ensure reproducibility. See
	              # https://www.mercurial-scm.org/help/topics/environment
                "HGRCPATH": None,
                "HGENCODINGMODE": None,
		            "HGENCODINGAMBIGUOUS": None,
		            "HGRCSKIPREPO": None,
		            "HGPLAIN": None,
            }
        ),
        working_directory = working_directory,
    )


def _hg_error(name, command, stderr):
    command_text = "hg " + " ".join([str(item).strip() for item in command])
    fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))


def _update_hg_attrs(orig, keys, override):
    result = update_attrs(orig, keys, override)

    # Only revision is needed, remove branch.
    if "revision" in result:
        result.pop("branch", None)
    return result


mercurial_repository = repository_rule(
    implementation = _mercurial_repository_implementation,
    attrs = _common_attrs,
    environ = [DEFAULT_CANONICAL_ID_ENV],
    doc = """Clone an external mercurial repository.

Clones a Mercurial repository. Mercurial will update the working directory to
the first applicable revision from this list:

1) nothing if the source repository has no changesets

2) the changeset specified with the 'revision' attribute

3) the tipmost head specified with 'branch' attribute

4) the tipmost head specified with the url#branch source syntax

5) the revision marked with the ‘@’ bookmark, if present

6) the tipmost head of the default branch

7) tip

Afterward, the rule will determine the changeset id of the commit that was
checked out, and return a dict with parameters that provide a reproducible
version of this rule (since a branch/tag/bookmark can change).

Prefer [`http_archive`](/rules/lib/repo/http#http_archive) to `mercurial_repository`.
The reasons are:

* Mercurial repository rules depend on system `hg(1)` whereas the HTTP
  downloader is built into Bazel and has no system dependencies.
* Mercurial doesn't have a native concept of shallow pulls - the whole
  repository history up to the revision of interest must be downloaded.
  Extensions exist to avoid this, but are not supported here.
* `http_archive` supports a list of `urls` as mirrors, while
  `mercurial_repository` supports only a single `remote`.
""",
)
