package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)

alias(
    name = "launcher",
    actual = "//src/tools/launcher:launcher",
)

alias(
    name = "launcher_maker",
    actual = "//src/tools/launcher:launcher_maker",
)
