// Copyright 2017 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by:
// @bazel_tools//tools/java/runfiles:java_current_repository

package com.google.devtools.build.runfiles;

public final class RunfilesConstants {

  public static final String CURRENT_REPOSITORY = "__CURRENT_REPOSITORY__";

  private RunfilesConstants() {}
}
