filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//tools/proto/private/rules:srcs",
    ],
    visibility = [
        "//tools/proto:__pkg__",
    ],
)

filegroup(
    name = "bzl_srcs",
    srcs = glob(["*.bzl"]) + [
        "//tools/proto/private/rules:bzl_srcs",
    ],
    visibility = [
        "//tools/proto:__pkg__",
    ],
)
