filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//configs/rbe/rbe_ubuntu1804_java11/cc:srcs",
        "//configs/rbe/rbe_ubuntu1804_java11/java:srcs",
        "//configs/rbe/rbe_ubuntu1804_java11/config:srcs",
    ],
    visibility = ["//configs/rbe:__subpackages__"],
)
