# Standard constraint_settings and constraint_values for Java.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "srcs",
    srcs = ["BUILD"],
)

constraint_setting(name = "runtime")

constraint_value(
    name = "jdk8",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk9",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk10",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk11",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk12",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk13",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk14",
    constraint_setting = ":runtime",
)

constraint_value(
    name = "jdk15",
    constraint_setting = ":runtime",
)

constraint_setting(name = "language")

constraint_value(
    name = "java7",
    constraint_setting = ":language",
)

constraint_value(
    name = "java8",
    constraint_setting = ":language",
)

constraint_value(
    name = "java9",
    constraint_setting = ":language",
)

constraint_value(
    name = "java10",
    constraint_setting = ":language",
)

constraint_value(
    name = "java11",
    constraint_setting = ":language",
)

constraint_value(
    name = "java12",
    constraint_setting = ":language",
)

constraint_value(
    name = "java13",
    constraint_setting = ":language",
)

constraint_value(
    name = "java14",
    constraint_setting = ":language",
)

constraint_value(
    name = "java15",
    constraint_setting = ":language",
)

constraint_setting(name = "location")

constraint_value(
    name = "local",
    constraint_setting = ":location",
)

constraint_value(
    name = "absolute",
    constraint_setting = ":location",
)

constraint_value(
    name = "remote",
    constraint_setting = ":location",
)
