load("//tools/build_defs/dotnet:csharp.bzl", "csharp_library")

csharp_library(
    name = "TransitiveClass",
    srcs = [
        "Properties/AssemblyInfo.cs",
        "TransitiveClass.cs",
    ],
    visibility = ["//visibility:public"],
)
