package(default_visibility = ["//visibility:public"])

# make a :colors target that any sass_binary rules can depend on.
filegroup(
    name = "colors",
    srcs = ["_colors.scss"],
)

# make a :fonts target that any sass_binary rules can depend on.
filegroup(
    name = "fonts",
    srcs = ["_fonts.scss"],
)

