# Rules for defining toolchains.

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

exports_files(
    glob(["**"]),
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)
