filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//tools/proto/private:srcs",
    ],
    visibility = [
        "//tools:__pkg__",
    ],
)

filegroup(
    name = "bzl_srcs",
    srcs = glob(["*.bzl"]) + [
        "//tools/proto/private:bzl_srcs",
    ],
    visibility = [
        "//tools:__pkg__",
    ],
)
