name: Community Review Labeler

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pull-requests: write

jobs:
  label_community_reviewed:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout master branch
        uses: actions/checkout@v6
        with:
          ref: master

      - name: Run Labeler Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/community_review_labeler.sh
