name: release-helper
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@8fae15fdb0532109a35cae0ca16041fc424c0a9b # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
