name: release-helper
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@ee5ba8422a610abe834d379252881d903890d560 # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
