name: release-helper
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@b083e2340a904ef1a3b7677c091dc59d3e73e154 # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
